version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run: echo 0
      - continuation/continue:
          configuration_path: src/continue-config.yml

workflows:
  setup:
    jobs:
      - setup