version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  build:
    executor: aws-ecr/default
    environment:
      AWS_ECR_REGISTRY_ID: "183081753049"
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          aws-access-key-id: ECR_AWS_ACCESS_KEY_ID
          aws-secret-access-key: ECR_AWS_SECRET_ACCESS_KEY
          repo: circleci/cerebro
          tag: ${CIRCLE_BRANCH}-$(git rev-parse --short ${CIRCLE_SHA1})
          push-image: false
          region: us-east-1
  build-and-push:
    executor: aws-ecr/default
    environment:
      AWS_ECR_REGISTRY_ID: "183081753049"
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          aws-access-key-id: ECR_AWS_ACCESS_KEY_ID
          aws-secret-access-key: ECR_AWS_SECRET_ACCESS_KEY
          repo: circleci/cerebro
          tag: ${CIRCLE_BRANCH}-$(git rev-parse --short ${CIRCLE_SHA1}),latest
          push-image: true
          region: us-east-1

workflows:
  workflow:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              ignore: main
      - build-and-push:
          context: org-global
          filters:
            branches:
              only: main
