# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2.1
executors:
  python:
    docker:
      - image: circleci/python:3.7.3
jobs:

  build:
    executor: python
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  test:
    executor: python
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: run pytest
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pytest

  send_report:
    executor: python
    working_directory: ~/repo
    steps:
      - checkout: {path: ~/repo}
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Send emails
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python perf_metrics/core.py insights_reporting_config.json

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build

  weekly-report:
    triggers:
      - schedule:
          cron: "0 9 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - send_report:
          requires:
            - build
