version: 2.1

workflows:
  version: 2
  ci:
    jobs:
      - test:
          context: org-global
      - publish:
          context: org-global
          requires:
            - test
          filters:
            branches:
              only: master

commands:
  save_jar_cache:
    steps:
      - save_cache:
          key: v1-jars-{{ checksum "project.clj" }}
          paths: [~/.m2]
  setup:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-jars-{{ checksum "project.clj" }}
            - v1-jars-

jobs:
  test:
    docker:
      - image: circleci/clojure-service:0.2-dev
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
      - image: circleci/fileserverd:0.2.36-793dbf2
        command: fileserverd
        environment:
          FILESERVER_USERNAME: qwer
          FILESERVER_PASSWORD: asdf
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
      - image: minio/minio:RELEASE.2018-10-25T01-27-03Z
        command: server /data
        environment:
          MINIO_ACCESS_KEY: "minio-access-key"
          MINIO_SECRET_KEY: "minio-secret-key"
    steps:
      - setup
      - run:
          command: lein cloverage --codecov
          environment:
            FILESERVER_USERNAME: qwer
            FILESERVER_PASSWORD: asdf
            MINIO_ACCESS_KEY: "minio-access-key"
            MINIO_SECRET_KEY: "minio-secret-key"
      - save_jar_cache
      - run:
          name: Upload coverage data
          command: |
            bash <(curl -s https://codecov.io/bash)

  publish:
    docker:
      - image: circleci/clojure-service:0.2-dev
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    steps:
      - setup
      - run: lein deploy circle-s3
      - save_jar_cache
