version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build .
  remove-dlc:
    docker:
      - image: cimg/base:2020.01
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker images --no-trunc --format '{{.ID}}' | xargs docker rmi
