version: 2.1

workflows:
  main:
    jobs:
      - lint:
          matrix:
            parameters:
              go_version:
                - '1.17'
                - '1.18'
      - test:
          name: test-<< matrix.go_version >>
          matrix:
            parameters:
              go_version:
                - '1.17'
                - '1.18'
      - release:
          requires:
            - lint
            - test
          filters:
            branches:
              only: main

jobs:

  lint:
    parameters:
      go_version:
        type: string
    docker:
      - image: cimg/go:<<parameters.go_version>>
    resource_class: large
    steps:
      - checkout
      - setup
      - run:
          name: Check rootcerts is up to date
          command: ./do check-rootcerts
      - run:
          name: Verify modules are tidy
          command: ./do check-gomod
      - run:
          name: Lint
          command: ./do lint-report
      - cleanup

  test:
    parameters:
      go_version:
        type: string
    docker:
      - image: cimg/go:<<parameters.go_version>>
      - image: circleci/postgres:13.3-ram
        environment:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: dbname
      - image: circleci/redis:5.0.6-alpine
        command: [ "--databases", "1000000" ]
      - image: rabbitmq:3.8-management-alpine
      - image: mongo:4.2
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_INITDB_DATABASE: dbname
    resource_class: large
    steps:
      - checkout:
          path: ~/project
      - setup
      - run:
          name: Run tests
          command: ./do test
      - cleanup

  release:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Configure Git
          command: |
            git config --global user.email "eng-execution@circleci.com"
            git config --global user.name "Execution Team"
      - run:
          name: Tag release
          command: ./do release

commands:
  setup:
    steps:
      - run:
          name: Adding GOPATH bin to PATH
          command: echo 'export PATH="$PATH:$(go env GOPATH)/bin"' >> "$BASH_ENV"
      - run:
          name: Install devtools
          command: ./do install-devtools
      - run:
          name: Make test-reports dir
          command: mkdir -p test-reports
      - run:
          name: Download dependencies
          command: go mod download

  cleanup:
    steps:
      - store_artifacts:
          path: test-reports
      - store_test_results:
          path: test-reports

