version: 2.1

executors:
  ccc:
    docker:
    - image: circleci/command-convenience:0.1
      auth:
        username: $DOCKER_HUB_USER
        password: $DOCKER_HUB_PASSWORD
    environment:
      NAME: guardduty-to-network-acl
      DOCKER_REGISTRY: ecr
      DOCKERFILE_PATH: Dockerfile
      DEPLOY_TYPE: helm
      NAMESPACE: security
      CUSTOM_CHART: ./guardduty-to-network-acl
      DEPLOY_CONTAINER_NAME: 183081753049.dkr.ecr.us-east-1.amazonaws.com/circleci/guardduty-to-network-acl
      # Disable Twistlock temporarily to allow enabling Renovate to bump dependencies
      TWISTLOCK_ENFORCE: "false"

jobs:
  scan:
    executor: ccc
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run: scan

  deploy:
    executor: ccc
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run: publish
      - run: deploy

workflows:
  version: 2
  deploy:
    jobs:
    - scan:
        context: org-global
        filters:
          branches:
            ignore: main
    - deploy:
        context: org-global
        filters:
          branches:
            only: main
