version: 2.1
orbs: 
  go: circleci/go@1.7.0

jobs:
  build:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          coverprofile: cover.out
          failfast: true
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: ./cover.out

workflows:
  main:
    jobs:
      - build