# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/migratorator-test:0.1
      - image: circleci/mongo:3.2.13
        command: [mongod, --smallfiles, --nojournal, --noprealloc, --port=27018]
      - image: circleci/mongo:3.2.13
        command: [mongod, --smallfiles, --nojournal, --noprealloc, --port=27019]

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: run tests
          command: |
            which ldconfig && sudo ldconfig
            make test
