version: 2.1

orbs:
  midje-with-mongo:
    jobs:
      test:
        parameters:
          clojure-version:
            description: "The version of Clojure to test with"
            type: string
          mongo-version:
            description: "The version of MongoDB to test against"
            type: string
        docker:
          - image: clojure:lein-2.9.1
          - image: mongo:<< parameters.mongo-version >>
        environment:
          - CLOJURE_VERSION: << parameters.clojure-version >>
        steps:
          - checkout
          - restore_cache:
              keys:
                - v1-m2-{{ checksum "project.clj" }}
          - run: lein deps
          - save_cache:
              key: v1-m2-{{ checksum "project.clj" }}
              paths:
                - ~/.m2
          - run: lein midje

workflows:
  test:
    jobs:
      - midje-with-mongo/test:
          name: "test-mongo-2.6-clojure-1.7.0"
          clojure-version: "1.7.0"
          mongo-version: "2.6"
      - midje-with-mongo/test:
          name: "test-mongo-3.0-clojure-1.7.0"
          clojure-version: "1.7.0"
          mongo-version: "3.0"
      - midje-with-mongo/test:
          name: "test-mongo-3.2-clojure-1.7.0"
          clojure-version: "1.7.0"
          mongo-version: "3.2"
      - midje-with-mongo/test:
          name: "test-mongo-3.4-clojure-1.7.0"
          clojure-version: "1.7.0"
          mongo-version: "3.4"
      - midje-with-mongo/test:
          name: "test-mongo-3.6-clojure-1.7.0"
          clojure-version: "1.7.0"
          mongo-version: "3.6"
      - midje-with-mongo/test:
          name: "test-mongo-2.6-clojure-1.8.0"
          clojure-version: "1.8.0"
          mongo-version: "2.6"
      - midje-with-mongo/test:
          name: "test-mongo-3.0-clojure-1.8.0"
          clojure-version: "1.8.0"
          mongo-version: "3.0"
      - midje-with-mongo/test:
          name: "test-mongo-3.2-clojure-1.8.0"
          clojure-version: "1.8.0"
          mongo-version: "3.2"
      - midje-with-mongo/test:
          name: "test-mongo-3.4-clojure-1.8.0"
          clojure-version: "1.8.0"
          mongo-version: "3.4"
      - midje-with-mongo/test:
          name: "test-mongo-3.6-clojure-1.8.0"
          clojure-version: "1.8.0"
          mongo-version: "3.6"
      - midje-with-mongo/test:
          name: "test-mongo-2.6-clojure-1.9.0"
          clojure-version: "1.9.0"
          mongo-version: "2.6"
      - midje-with-mongo/test:
          name: "test-mongo-3.0-clojure-1.9.0"
          clojure-version: "1.9.0"
          mongo-version: "3.0"
      - midje-with-mongo/test:
          name: "test-mongo-3.2-clojure-1.9.0"
          clojure-version: "1.9.0"
          mongo-version: "3.2"
      - midje-with-mongo/test:
          name: "test-mongo-3.4-clojure-1.9.0"
          clojure-version: "1.9.0"
          mongo-version: "3.4"
      - midje-with-mongo/test:
          name: "test-mongo-3.6-clojure-1.9.0"
          clojure-version: "1.9.0"
          mongo-version: "3.6"
      - midje-with-mongo/test:
          name: "test-mongo-2.6-clojure-1.10.1"
          clojure-version: "1.10.1"
          mongo-version: "2.6"
      - midje-with-mongo/test:
          name: "test-mongo-3.0-clojure-1.10.1"
          clojure-version: "1.10.1"
          mongo-version: "3.0"
      - midje-with-mongo/test:
          name: "test-mongo-3.2-clojure-1.10.0"
          clojure-version: "1.10.0"
          mongo-version: "3.2"
      - midje-with-mongo/test:
          name: "test-mongo-3.4-clojure-1.10.0"
          clojure-version: "1.10.0"
          mongo-version: "3.4"
      - midje-with-mongo/test:
          name: "test-mongo-3.6-clojure-1.10.0"
          clojure-version: "1.10.0"
          mongo-version: "3.6"
