version: 2.1
jobs:
  test:
    docker:
      - image: cimg/go:1.18
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Run unit tests
          command: |
            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
            gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- $PACKAGE_NAMES
      - store_test_results:
          path: /tmp/test-results
  build:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run: .circleci/run-goreleaser.sh release --snapshot
  release:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run: .circleci/run-goreleaser.sh release

workflows:
  main:
    jobs:
      - test
      - build:
          filters:
            tags:
              ignore: /.*/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
          context:
            - mongoctl
