version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13
  docker: circleci/docker@1.3.0

executors:
  linuxgo:
    parameters:
    working_directory: /go/src/github.com/honeycombio/samproxy
    docker:
      - image: circleci/golang:1.14
  ccc:
    docker:
      - image: circleci/command-convenience:0.1
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD

commands:
  go-build:
    parameters:
      os:
        description: Target operating system
        type: enum
        enum: ["linux", "darwin"]
        default: "linux"
      arch:
        description: Target architecture
        type: enum
        enum: ["amd64", "arm64"]
        default: "amd64"
    steps:
      - run: |
          GOOS=<< parameters.os >> \
          GOARCH=<< parameters.arch >> \
          go build -ldflags "-X main.BuildID=${CIRCLE_TAG}" \
          -o $GOPATH/bin/samproxy-<< parameters.os >>-<< parameters.arch >> \
          ./cmd/samproxy
  ccc-publish:
    parameters:
      docker_registry:
        type: enum
        enum: ["all", "none"]
        default: "none"
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: publish
          environment:
            NAME: samproxy
            # Use version 0 to avoid colliding with official Samproxy releases.
            MAJOR_VERSION: "0.0"
            DOCKERFILE_PATH: Dockerfile.circleci
            DOCKER_REGISTRY: <<parameters.docker_registry>>

jobs:
  test:
    executor: linuxgo
    steps:
      - checkout
      - run:
          name: go_test
          command: go test --timeout 10s -v ./...

  build:
    executor: linuxgo
    steps:
      - checkout
      - go-build:
          os: linux
          arch: amd64
      - go-build:
          os: linux
          arch: arm64
      - go-build:
          os: darwin
          arch: amd64
      - run:
          name: apt_get_update
          command: sudo apt-get -qq update
      - run:
          name: apt_get_install
          command: sudo apt-get install -y build-essential rpm ruby ruby-dev
      - run:
          name: gem_install
          command: sudo gem install fpm
      - run: mkdir -p ~/artifacts
      - run:
          name: build_deb_amd64
          command: ./build-pkg.sh -m amd64 -v "${CIRCLE_TAG}" -t deb && mv *.deb ~/artifacts
      - run:
          name: build_deb_arm64
          command: ./build-pkg.sh -m arm64 -v "${CIRCLE_TAG}" -t deb && mv *.deb ~/artifacts
      - run:
          name: build_rpm_amd64
          command: ./build-pkg.sh -m amd64 -v "${CIRCLE_TAG}" -t rpm && mv *.rpm ~/artifacts
      - run:
          name: copy_binaries
          command: cp $GOPATH/bin/samproxy-* ~/artifacts
      - run: echo "finished builds" && find ~/artifacts -ls
      - persist_to_workspace:
          root: ~/
          paths:
            - artifacts
      - store_artifacts:
          path: ~/artifacts

  publish_github:
    docker:
      - image: cibuilds/github:0.13.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "Publish Release on GitHub"
          command: |
            echo "about to publish to tag ${CIRCLE_TAG}"
            ls -l ~/artifacts/*
            ghr -draft -n ${CIRCLE_TAG} -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ~/artifacts

  publish_s3:
    executor: linuxgo
    steps:
      - attach_workspace:
          at: ~/
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - run:
          name: sync_s3_artifacts
          command: aws s3 sync ~/artifacts s3://honeycomb-builds/honeycombio/samproxy/${CIRCLE_TAG}/

  publish_circleci_dry_run:
    executor: ccc
    steps:
      - ccc-publish:
          docker_registry: none

  publish_circleci:
    executor: ccc
    steps:
      - ccc-publish:
          docker_registry: all

workflows:
  build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /.*/
      - publish_github:
          context: Honeycomb Secrets
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish_s3:
          context: Honeycomb Secrets
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

      - publish_circleci_dry_run:
          context: org-global
          requires:
            - build
          filters:
            branches:
              ignore: cci-main

      - publish_circleci:
          context: org-global
          requires:
            - build
          filters:
            branches:
              only: cci-main
