version: 2.1
jobs:
  build_1:
    docker:
      - image: circleci/node
    steps:
      - run: exit 0

  build_2:
    docker:
      - image: circleci/node
    steps:
      - run: exit 0

workflows:
  version: 2
  build:
    jobs:
      - build_1
      - build_2
