#########################################
#         REUSABLE YAML ANCHORS         #
#########################################
install_deps: &install_deps
  run:
    name: Installing Dependencies
    command: |
      apk add curl bash
      apk add python3
      apk add py-pip
      apk add jq
      pip install awscli
      sh -c "curl https://raw.githubusercontent.com/kadwanev/retry/master/retry -o /usr/local/bin/retry && chmod +x /usr/local/bin/retry"


create_env: &create_env
  run:
    name: Creating Test Environment
    command: |
      cd $TEST_DIR
      terraform init
      # Piping Terraform Plan to /dev/null to prevent secrets from being displayed in CI output
      terraform plan -var="prefix=nc-asg-$CIRCLE_BUILD_NUM" > /dev/null
      terraform apply -var="prefix=nc-asg-$CIRCLE_BUILD_NUM" -auto-approve

verify_nomad_asg: &verify_nomad_asg
  run:
    name: Verifying ASG Instance Creation
    shell: /bin/bash
    command: |
      INSTANCE_COUNT=0
      COUNT=0
      while [[ "$INSTANCE_COUNT" -ne "2" && "$COUNT" -lt "24" ]]
      do
        echo "Waiting for Instance Creation... $((( $INSTANCE_COUNT * 1 ))) created...  $((( $COUNT * 5 )))s"
        INSTANCE_COUNT=$(aws ec2 describe-instances --region "us-east-1" \
                        --filters "Name=tag:Name,Values=nc-asg-$CIRCLE_BUILD_NUM*" | \
                        jq '.Reservations[].Instances[].InstanceId' | \
                        wc -l)
        sleep 5
        ((COUNT++))
      done
      if [ $COUNT -lt 24 ]; then echo exit 0; else echo exit 1; fi     

destroy_env: &destroy_env
  run:
    name: Destroying Test Environment
    when: always
    command: |
      cd $TEST_DIR
      terraform destroy -var="prefix=nc-asg-$CIRCLE_BUILD_NUM" -auto-approve


#########################################
#            CIRCLE CONFIG              #
#########################################
version: 2
jobs:
  standard-nomad-client-asg:
    docker:
      - image: hashicorp/terraform:light
    environment:
      TEST_DIR: "examples/standard"
      USE_DOMAIN: false
    steps:
      - checkout
      - <<: *install_deps
      - <<: *create_env
      - <<: *verify_nomad_asg
      - <<: *destroy_env
          
workflows:
  version: 2
  tests:
    jobs:
      - standard-nomad-client-asg