version: 2.1

jobs:
  publish-vm-service-lite:
    docker:
      - image: circleci/golang:1.13
    steps:
      - setup_remote_docker
      - checkout
      - run: go mod download
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build
      - run:
          name: build docker image
          command: |
            TAG="1.0.${CIRCLE_BUILD_NUM}-$(git rev-parse --short HEAD)"
            docker build . -t "circleci/vm-service-lite:${TAG}"

            if [ "${CIRCLE_BRANCH}" == "master" ] ; then
              docker login -u "${DOCKER_HUB_USER}" -p "${DOCKER_HUB_PASSWORD}"
              docker push "circleci/vm-service-lite:${TAG}"
            fi

  publish-sshd:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: build docker image
          command: |
            tag="circleci/sshd:0.1.${CIRCLE_BUILD_NUM}-$(git rev-parse --short HEAD)"
            docker build sshd -t "${tag}"

            if [ "${CIRCLE_BRANCH}" == "master" ] ; then
              docker login -u "${DOCKER_HUB_USER}" -p "${DOCKER_HUB_PASSWORD}"
              docker tag "${tag}" "circleci/sshd:0.1"
              docker push "${tag}"
              docker push "circleci/sshd:0.1"
            fi

workflows:
  workflow:
    jobs:
      - publish-vm-service-lite:
          context: org-global
      - publish-sshd:
          context: org-global
