version: 2.1
orbs:
  web-ui-orb: sandbox/web-ui-orb@5.1.0

references:
  version_js: &version_js 12
  version_cypress: &version_cypress 1
  image_name: web-ui-support
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - web-ui-orb/dependencies:
          name: dependencies
          context: web-ui-npm
          cache_version_js_dependencies: *version_js
          cache_version_cypress_dependencies: *version_cypress
      - web-ui-orb/storybook-build:
          name: storybook-build
          build_storybook_command: NODE_ENV=test yarn build-storybook -s ./src
          cache_version_js_dependencies: *version_js
          requires:
            - dependencies
      - web-ui-orb/test:
          name: test
          cache_version_js_dependencies: *version_js
          requires:
            - dependencies
      - web-ui-orb/chromatic-snapshot:
          name: chromatic-snapshot
          cache_version_js_dependencies: *version_js
          requires:
            - dependencies
            - storybook-build
      - web-ui-orb/test-production-docker-image:
          name: test-production-docker-image
          image_name: web-ui-support
          cache_version_js_dependencies: *version_js
          requires:
            - dependencies
          context: [org-global, web-ui-npm]
      - web-ui-orb/build-and-deploy-static:
          cache_version_js_dependencies: *version_js
          name: build-and-deploy-static
          bucket_name: 'circleci-web-ui-support-assets'
          cdn_url: 'https://assets-support.circleci.com'
          context: [web-ui-support-assets, web-ui-npm, web-ui-datadog]
          filters:
            branches:
              only:
                - main
                - canary
          requires:
            - dependencies
      - web-ui-orb/build-static:
          name: build-static
          cache_version_js_dependencies: *version_js
          requires:
            - dependencies
          filters:
            branches:
              ignore:
                - main
                - canary
      - web-ui-orb/build-and-publish-container:
          name: scan-vulnerabilities
          image_name: web-ui-support
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
          context: [web-ui-npm, org-global]
          scan_only: true
          filters:
            branches:
              ignore:
                - main
                - canary
          requires:
            - build-static
      - web-ui-orb/build-and-publish-container:
          name: publish
          image_name: web-ui-support
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
          context: [web-ui-npm, org-global]
          filters:
            branches:
              only: main
          requires:
            - test
            - build-and-deploy-static
            - test-production-docker-image
      - web-ui-orb/deploy-container:
          name: deploy
          image_name: web-ui-support
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
          context: [web-ui-npm, org-global]
          filters:
            branches:
              only: main
          requires:
            - publish
      - web-ui-orb/build-and-publish-container:
          name: publish-canary
          image_name: web-ui-support
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
          context: [web-ui-npm, org-global]
          filters:
            branches:
              only: canary
          requires:
            - test
            - build-and-deploy-static
            - test-production-docker-image
      - web-ui-orb/deploy-container:
          name: deploy-canary
          image_name: web-ui-support
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
          context: [web-ui-npm, org-global]
          release_version: canary
          values_file: k8s-canary-values.yml
          filters:
            branches:
              only: canary
          requires:
            - publish-canary
