version: 2.1

orbs:
  slack: circleci/slack@2.6.0
  web-ui-orb: sandbox/web-ui-orb@5.0.1
  scotty-orb: cci-releng/scotty-orb@0.0.2

references:
  version_js: &version_js 5
  version_cypress: &version_cypress 1
  launch_darkly_client_key: &launch_darkly_client_key 5d4c4c6e60697a07ca0ac566
  optimizely_sdk_key: &optimizely_sdk_key GfYszBpMkefBSwiiEkH3b3
  hostname: &hostname app.circleci.com

workflows:
  version: 2

  build-test-and-deploy:
    jobs:
      - web-ui-orb/dependencies:
          name: dependencies
          context: web-ui-npm
          cache_version_js_dependencies: *version_js
          cache_version_cypress_dependencies: *version_cypress
      - web-ui-orb/test:
          name: test
          cache_version_js_dependencies: *version_js
          requires:
            - dependencies
      - web-ui-orb/chromatic-snapshot:
          name: chromatic-snapshot
          cache_version_js_dependencies: *version_js
          requires:
            - dependencies
      - web-ui-orb/test-production-docker-image:
          name: test-production-docker-image
          image_name: web-ui-project-settings
          cache_version_js_dependencies: *version_js
          launch_darkly_client_side_id: *launch_darkly_client_key
          optimizely_sdk_key: *optimizely_sdk_key
          hostname: *hostname
          requires:
            - dependencies
          context: web-ui-npm
      - web-ui-orb/build-and-deploy-static:
          cache_version_js_dependencies: *version_js
          name: build-and-deploy-static
          bucket_name: circleci-web-ui-project-settings-assets/settings/project
          build_dir: .next
          cdn_url: https://assets-project-settings.circleci.com/settings/project
          context: [web-ui-project-settings-assets, web-ui-npm, web-ui-datadog]
          launch_darkly_client_side_id: *launch_darkly_client_key
          filters:
            branches:
              only:
                - master
                - canary
          requires:
            - dependencies
      - web-ui-orb/build-and-publish-container:
          name: publish
          image_name: web-ui-project-settings
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
          context: [web-ui-npm, org-global]
          filters:
            branches:
              only:
                - master
                - /^server-\d\..+/
          requires:
            - build-and-deploy-static
            - test
            - test-production-docker-image
            - chromatic-snapshot
      - web-ui-orb/deploy-container:
          name: deploy
          image_name: web-ui-project-settings
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
          context: [web-ui-npm, org-global]
          filters:
            branches:
              only: master
          requires:
            - publish
      - scotty-orb/promote-to-server:
          name: promote-to-server
          context: org-global
          promotion_component_list: 'circleci/web-ui-project-settings'
          requires:
            - publish
      - web-ui-orb/build-and-publish-container:
          name: publish-canary
          image_name: web-ui-project-settings
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
          context: [web-ui-npm, org-global]
          filters:
            branches:
              only: canary
          requires:
            - test
            - build-and-deploy-static
            - test-production-docker-image
      - web-ui-orb/deploy-container:
          name: deploy-canary
          image_name: web-ui-project-settings
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
          context: [web-ui-npm, org-global]
          release_version: canary
          values_file: k8s-canary-values.yml
          requires:
            - publish-canary
